INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (30, 'John', 'Doe');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (25, 'Alice', 'Roe');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (36, 'Jane', 'Woe');